class Add2013Challenge < ActiveRecord::Migration
  def up
    challenge = Challenge.create! :year => Date.parse('2013-01-01'), :title => 'Challenge 2013', :url => 'http://www.flickr.com/groups/challenge2013/'
    Week.create! :challenge_id => challenge.id, :week_number => 1, :subject => 'Silhouettes'
    Week.create! :challenge_id => challenge.id, :week_number => 2, :subject => 'Self portraits'
    Week.create! :challenge_id => challenge.id, :week_number => 3, :subject => 'Mono'
    Week.create! :challenge_id => challenge.id, :week_number => 4, :subject => 'Looking up/down'
    Week.create! :challenge_id => challenge.id, :week_number => 5, :subject => 'Slow shutter'
    Week.create! :challenge_id => challenge.id, :week_number => 6, :subject => 'Strangers /Candids'
    Week.create! :challenge_id => challenge.id, :week_number => 7, :subject => 'Doors'
    Week.create! :challenge_id => challenge.id, :week_number => 8, :subject => 'Abstracts'
    Week.create! :challenge_id => challenge.id, :week_number => 9, :subject => 'Still life'
    Week.create! :challenge_id => challenge.id, :week_number => 10, :subject => 'Contrasts'
    Week.create! :challenge_id => challenge.id, :week_number => 11, :subject => 'Within a 15 minute walk from your house'
    Week.create! :challenge_id => challenge.id, :week_number => 12, :subject => 'Minimalism'
    Week.create! :challenge_id => challenge.id, :week_number => 13, :subject => 'Your version of a famous photo or painting'
    Week.create! :challenge_id => challenge.id, :week_number => 14, :subject => '35mm (or other fixed focal length)'
    Week.create! :challenge_id => challenge.id, :week_number => 15, :subject => 'Night photography'
    Week.create! :challenge_id => challenge.id, :week_number => 16, :subject => 'Fences'
    Week.create! :challenge_id => challenge.id, :week_number => 17, :subject => 'Use software to create a composite'
    Week.create! :challenge_id => challenge.id, :week_number => 18, :subject => 'Portraits'
    Week.create! :challenge_id => challenge.id, :week_number => 19, :subject => 'A photo of the same subject for 7days'
    Week.create! :challenge_id => challenge.id, :week_number => 20, :subject => 'Blur'
    Week.create! :challenge_id => challenge.id, :week_number => 21, :subject => 'Holes'
    Week.create! :challenge_id => challenge.id, :week_number => 22, :subject => 'Ice'
    Week.create! :challenge_id => challenge.id, :week_number => 23, :subject => 'Panning'
    Week.create! :challenge_id => challenge.id, :week_number => 24, :subject => 'Architecture'
    Week.create! :challenge_id => challenge.id, :week_number => 25, :subject => 'Body parts ( keep it clean folks ;)'
    Week.create! :challenge_id => challenge.id, :week_number => 26, :subject => 'Textures'
    Week.create! :challenge_id => challenge.id, :week_number => 27, :subject => 'Wildlife'
    Week.create! :challenge_id => challenge.id, :week_number => 28, :subject => 'Transport'
    Week.create! :challenge_id => challenge.id, :week_number => 29, :subject => 'Friendship'
    Week.create! :challenge_id => challenge.id, :week_number => 30, :subject => 'Trees'
    Week.create! :challenge_id => challenge.id, :week_number => 31, :subject => 'Flash photography'
    Week.create! :challenge_id => challenge.id, :week_number => 32, :subject => 'Food/Edibles/Consumables/ Beverages'
    Week.create! :challenge_id => challenge.id, :week_number => 33, :subject => 'Something spotty/dotty'
    Week.create! :challenge_id => challenge.id, :week_number => 34, :subject => 'Macro'
    Week.create! :challenge_id => challenge.id, :week_number => 35, :subject => 'People at work'
    Week.create! :challenge_id => challenge.id, :week_number => 36, :subject => 'Forced perspective'
    Week.create! :challenge_id => challenge.id, :week_number => 37, :subject => 'As seen on TV'
    Week.create! :challenge_id => challenge.id, :week_number => 38, :subject => 'Symmetry'
    Week.create! :challenge_id => challenge.id, :week_number => 39, :subject => 'A shape (round, square, etc)'
    Week.create! :challenge_id => challenge.id, :week_number => 40, :subject => 'Panorama'
    Week.create! :challenge_id => challenge.id, :week_number => 41, :subject => 'Water'
    Week.create! :challenge_id => challenge.id, :week_number => 42, :subject => 'Landscape'
    Week.create! :challenge_id => challenge.id, :week_number => 43, :subject => 'High contrast'
    Week.create! :challenge_id => challenge.id, :week_number => 44, :subject => 'Colour'
    Week.create! :challenge_id => challenge.id, :week_number => 45, :subject => 'Fire'
    Week.create! :challenge_id => challenge.id, :week_number => 46, :subject => 'Tilt shift'
    Week.create! :challenge_id => challenge.id, :week_number => 47, :subject => 'Bridges'
    Week.create! :challenge_id => challenge.id, :week_number => 48, :subject => 'Benches or places to sit'
    Week.create! :challenge_id => challenge.id, :week_number => 49, :subject => 'Zoom burst'
    Week.create! :challenge_id => challenge.id, :week_number => 50, :subject => 'Lightpainting'
    Week.create! :challenge_id => challenge.id, :week_number => 51, :subject => 'Multiple exposure'
    Week.create! :challenge_id => challenge.id, :week_number => 52, :subject => 'Reflections'
  end

  def down
    challenge = Challenge.where(:year => Date.parse('2013-01-01'))
    Week.where(:challenge_id => challenge.id).destroy_all
    Challenge.destroy(challenge.id)
  end
end
