class Add2014Challenge < ActiveRecord::Migration
  def up
    challenge = Challenge.create! :year => Date.parse('2014-01-01'), :title => 'Challenge 2014', :url => 'http://www.flickr.com/groups/challenge2014/'
    Week.create! :challenge_id => challenge.id, :week_number => 1, :subject => 'Chocolate'
    Week.create! :challenge_id => challenge.id, :week_number => 2, :subject => 'Swirls'
    Week.create! :challenge_id => challenge.id, :week_number => 3, :subject => 'Hats'
    Week.create! :challenge_id => challenge.id, :week_number => 4, :subject => 'Sepia-toned'
    Week.create! :challenge_id => challenge.id, :week_number => 5, :subject => 'Home'
    Week.create! :challenge_id => challenge.id, :week_number => 6, :subject => 'Posterisation'
    Week.create! :challenge_id => challenge.id, :week_number => 7, :subject => 'Low key'
    Week.create! :challenge_id => challenge.id, :week_number => 8, :subject => 'Behind the scenes'
    Week.create! :challenge_id => challenge.id, :week_number => 9, :subject => 'Windows'
    Week.create! :challenge_id => challenge.id, :week_number => 10, :subject => 'A memorial'
    Week.create! :challenge_id => challenge.id, :week_number => 11, :subject => 'Long Exposure '
    Week.create! :challenge_id => challenge.id, :week_number => 12, :subject => 'Lunchtime'
    Week.create! :challenge_id => challenge.id, :week_number => 13, :subject => 'The Sign Says'
    Week.create! :challenge_id => challenge.id, :week_number => 14, :subject => 'Nostalgic'
    Week.create! :challenge_id => challenge.id, :week_number => 15, :subject => 'One Shot, Two Ways'
    Week.create! :challenge_id => challenge.id, :week_number => 16, :subject => 'Layers'
    Week.create! :challenge_id => challenge.id, :week_number => 17, :subject => 'Shadow patterns'
    Week.create! :challenge_id => challenge.id, :week_number => 18, :subject => 'Horizon'
    Week.create! :challenge_id => challenge.id, :week_number => 19, :subject => 'Saturated'
    Week.create! :challenge_id => challenge.id, :week_number => 20, :subject => 'Curves'
    Week.create! :challenge_id => challenge.id, :week_number => 21, :subject => 'Mechanical'
    Week.create! :challenge_id => challenge.id, :week_number => 22, :subject => 'Leaves/foliage'
    Week.create! :challenge_id => challenge.id, :week_number => 23, :subject => 'Focus'
    Week.create! :challenge_id => challenge.id, :week_number => 24, :subject => 'Rivers/canals/lakes (must be inland waterways)'
    Week.create! :challenge_id => challenge.id, :week_number => 25, :subject => 'Churches'
    Week.create! :challenge_id => challenge.id, :week_number => 26, :subject => 'Dilapidation/ruins/seen better days.'
    Week.create! :challenge_id => challenge.id, :week_number => 27, :subject => 'An Unusual Point Of View'
    Week.create! :challenge_id => challenge.id, :week_number => 28, :subject => 'Infinite'
    Week.create! :challenge_id => challenge.id, :week_number => 29, :subject => 'Boats'
    Week.create! :challenge_id => challenge.id, :week_number => 30, :subject => 'Colour'
    Week.create! :challenge_id => challenge.id, :week_number => 31, :subject => 'In the Background'
    Week.create! :challenge_id => challenge.id, :week_number => 32, :subject => 'Good Morning!'
    Week.create! :challenge_id => challenge.id, :week_number => 33, :subject => 'Rears'
    Week.create! :challenge_id => challenge.id, :week_number => 34, :subject => 'Trains/buses/public transport'
    Week.create! :challenge_id => challenge.id, :week_number => 35, :subject => 'Statuary'
    Week.create! :challenge_id => challenge.id, :week_number => 36, :subject => 'Shoes'
    Week.create! :challenge_id => challenge.id, :week_number => 37, :subject => 'A big sky'
    Week.create! :challenge_id => challenge.id, :week_number => 38, :subject => 'High key'
    Week.create! :challenge_id => challenge.id, :week_number => 39, :subject => 'My Neighbourhood'
    Week.create! :challenge_id => challenge.id, :week_number => 40, :subject => 'Tools'
    Week.create! :challenge_id => challenge.id, :week_number => 41, :subject => 'A Day in My Life (multi-photo challenge)'
    Week.create! :challenge_id => challenge.id, :week_number => 42, :subject => 'Seascape'
    Week.create! :challenge_id => challenge.id, :week_number => 43, :subject => 'Change'
    Week.create! :challenge_id => challenge.id, :week_number => 44, :subject => 'Timepieces'
    Week.create! :challenge_id => challenge.id, :week_number => 45, :subject => 'Illumination'
    Week.create! :challenge_id => challenge.id, :week_number => 46, :subject => 'Lamp light'
    Week.create! :challenge_id => challenge.id, :week_number => 47, :subject => 'Inside'
    Week.create! :challenge_id => challenge.id, :week_number => 48, :subject => 'Eerie'
    Week.create! :challenge_id => challenge.id, :week_number => 49, :subject => 'Trees with no leaves'
    Week.create! :challenge_id => challenge.id, :week_number => 50, :subject => 'HDR'
    Week.create! :challenge_id => challenge.id, :week_number => 51, :subject => 'Pattern'
    Week.create! :challenge_id => challenge.id, :week_number => 52, :subject => 'Let There Be Light!'
  end

  def down
    challenge = Challenge.where(:year => Date.parse('2014-01-01'))
    Week.where(:challenge_id => challenge.id).destroy_all
    Challenge.destroy(challenge.id)
  end
end
